#!/usr/bin/env python3
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "generated" / "mcp-contract"
SCHEMA_DIR = ROOT / "schema"
APP_FILE = ROOT / "app.py"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(8192)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def collect_api_routes(app_file: Path):
    text = app_file.read_text(encoding="utf-8")
    route_re = re.compile(r"@app\.route\('([^']+)'(?:,\s*methods=\[([^\]]+)\])?\)")
    routes = []
    for match in route_re.finditer(text):
        path = match.group(1)
        methods_literal = match.group(2)
        methods = ["GET"]
        if methods_literal:
            methods = [m.strip().strip("'\"") for m in methods_literal.split(",") if m.strip()]
        routes.append({"path": path, "methods": methods})
    return routes


def copy_schemas():
    out_schema_dir = OUT_DIR / "schema"
    out_schema_dir.mkdir(parents=True, exist_ok=True)
    schema_hashes = {}
    for schema_file in sorted(SCHEMA_DIR.glob("*.json")):
        target = out_schema_dir / schema_file.name
        target.write_text(schema_file.read_text(encoding="utf-8"), encoding="utf-8")
        schema_hashes[schema_file.name] = sha256_file(schema_file)
    return schema_hashes


def read_version() -> str:
    version_file = ROOT / "VERSION"
    if not version_file.exists():
        return "dev"
    return version_file.read_text(encoding="utf-8").strip() or "dev"


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    schema_hashes = copy_schemas()
    routes = collect_api_routes(APP_FILE)

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_repo": "Aephir/cocktail-recipes",
        "version": read_version(),
        "files": {
            "app.py": sha256_file(APP_FILE),
            "README.md": sha256_file(ROOT / "README.md"),
            "VERSION": sha256_file(ROOT / "VERSION"),
        },
        "schemas": schema_hashes,
        "api_routes": routes,
        "mcp_capabilities": {
            "dry_run_mutations": True,
            "ingredient_merge": True,
            "tool_merge": True,
            "recipe_bulk_update": True,
            "operation_log": True,
        },
    }

    (OUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (OUT_DIR / "README.md").write_text(
        "# Generated MCP Contract Bundle\n\n"
        "This directory is generated by scripts/export_mcp_contract.py.\n"
        "Do not edit files here manually.\n",
        encoding="utf-8",
    )
    print(f"Wrote contract bundle to {OUT_DIR}")


if __name__ == "__main__":
    main()
